name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Cypress:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6

      - run: pnpm i --frozen-lockfile
      - run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          # we have already installed all dependencies above
          install: false
          command: pnpm test:headless

      # - name: Upload coverage
      #   uses: codecov/codecov-action@v2
      #   with:
      #     fail_ci_if_error: true
